### ISSUE TITLE
cannot install correctly

### ISSUE THREAD

**Issue by canfoderiskii** [aki77/atom-autocomplete-ctags#13]
Atom version: 1.7.2

Here is the error output:

> > runas@3.1.1 install C:\Users\Geminii\AppData\Local\Temp\apm-install-dir-116320-4328-1d82gvr\node_modules\autocomplete-ctags\node_modules\pathwatcher\node_modules\runas
> > node-gyp rebuild
> C:\Users\Geminii\AppData\Local\Temp\apm-install-dir-116320-4328-1d82gvr\node_modules\autocomplete-ctags\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "D:\Green software\Atom\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
> > ctags@3.0.0 install C:\Users\Geminii\AppData\Local\Temp\apm-install-dir-116320-4328-1d82gvr\node_modules\autocomplete-ctags\node_modules\ctags
> > node-gyp rebuild
> C:\Users\Geminii\AppData\Local\Temp\apm-install-dir-116320-4328-1d82gvr\node_modules\autocomplete-ctags\node_modules\ctags>if not defined npm_config_node_gyp (node "D:\Green software\Atom\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
> gypgypnpm ERR! Windows_NT 6.2.9200
> npm ERR! argv "D:\Green software\Atom\resources\app\apm\bin\node.exe" "D:\Green software\Atom\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "D:\Green software\Atom\.atom\.apm\.apmrc" "--userconfig" "D:\Green software\Atom\.atom\.apmrc" "install" "C:\Users\Geminii\AppData\Local\Temp\d-116320-4328-1gqhfya\package.tgz" "--target=0.36.8" "--arch=ia32"
> npm ERR! node v0.10.40
> npm ERR! npm  v2.13.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! ctags@3.0.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the ctags@3.0.0 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the ctags package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls ctags
> npm ERR! There is likely additional logging output above.

i am new to Atom editor, how should i do to correctly install from editor's Setting-install page.

**Comment by aki77** [comment]
I can't reproduce the error.
Please try re-install.

```
apm uninstall autocomplete-ctags
apm install autocomplete-ctags
```

**Comment by canfoderiskii** [comment]
I's used GUI setting page to install the autocomplete-ctags before. i tried multiple times but got the same error.

i also tried the command u gave me "apm (un)install autocomplete-ctags", still got the same error messages.

**Comment by canfoderiskii** [comment]
@aki77 I digged some infomation about node-gyp. It seems that python 2.7 and visual studio 2013 are needed. Then I have to ask, does the community version of vs2013 satisfy the requirements of node-gyp?

**Comment by canfoderiskii** [comment]
@aki77 Problem solved! 

In general, I have to install python 2.7, visual studio 2013 and python module gyp.
