### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by andbuitra** [aki77/atom-autocomplete-ctags#15]
Steps to reproduce: 
1. Open the editor.

Content of the error:

build@ – Cannot find module '/home/[user]/.atom/packages/autocomplete-ctags/node_modules/ctags/build'
build@ – Cannot find module '/home/[user]/.atom/packages/autocomplete-ctags/node_modules/pathwatcher/build'
build@ – Cannot find module '/home/[user]/.atom/packages/autocomplete-ctags/node_modules/pathwatcher/node_modules/runas/build'

Atom version: 1.7.1
autocomplete-ctags version: 0.4.1
OS: ElementaryOS (Ubuntu 14.04)

**Comment by andbuitra** [comment]
Rebuild after restarting PC solved the issue.

**Comment by aki77** [comment]
😃
