### ISSUE TITLE
Duplicate symbols when using snippers

### ISSUE THREAD

**Issue by junrrein** [aki77/atom-autocomplete-ctags#2]
If any of the open files already have a reference to a function (that exists in the ctags file) it will be shown twice on the autocomplete list: once with the parameters (generated by the snipper) and another time without them (what the autocomplete-plus package generates when autocomplete-ctags isn't present). 

![captura de pantalla de 2015-07-01 00-59-42](https://cloud.githubusercontent.com/assets/962049/8447289/8fcb9130-1f8c-11e5-980b-7947b103bd2f.png)

When the snipping system is disabled in options, there are no duplicate symbols.

![captura de pantalla de 2015-07-01 01-01-01](https://cloud.githubusercontent.com/assets/962049/8447300/ae723ac6-1f8c-11e5-89a2-d89865eea4b6.png)

Tested on autocomplete-ctags 0.2.1.

**Comment by junrrein** [comment]
This can be worked around by disabling the "Enable Built-In Provider" option in the autocomplete-plus settings.

**Comment by aki77** [comment]
problem of autocomplete-plus. :cry: 

https://github.com/atom/autocomplete-plus/blob/9b8041fb0e675dba23e7d7407097ce7cf9bb1c29/lib/autocomplete-manager.coffee#L288
