### ISSUE TITLE
Failed to require the main module of 'autocomplete-ctags' because it requires an incompatible native module.

### ISSUE THREAD

**Issue by martin-svk** [aki77/atom-autocomplete-ctags#4]
...Run `apm rebuild` in the package directory to resolve.

Running apm rebuild didnt help. I guess you are probably using some outdated atom API?

**Comment by aki77** [comment]
Please try the latest version.

**Comment by martin-svk** [comment]
Thanks, after downloading newest version and rebuilding package, it works.

**Comment by aki77** [comment]
:smiley:

**Comment by flplv** [comment]
~~This problem persists in Ubuntu 15.04 x86, Atom 1.4.3, and autocomplete-ctags 0.4.0~~
Actually, you need to have ctags installed in the system... duh!
