### ISSUE TITLE
Updating to 0.3.2 fails on Mac OS X Yosemite

### ISSUE THREAD

**Issue by bjoernd** [aki77/atom-autocomplete-ctags#5]
Output (:

> runas@3.1.0 install /private/var/folders/w_/4xqmt6ws6793zj5bxj8n3rf5j8lpyl/T/apm-install-dir-11596-96939-ws8z49/node_modules/autocomplete-ctags/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o
  CXX(target) Release/obj.target/runas/src/runas_darwin.o
  CXX(target) Release/obj.target/runas/src/fork.o
  SOLINK_MODULE(target) Release/runas.node

> ctags@3.0.0 install /private/var/folders/w_/4xqmt6ws6793zj5bxj8n3rf5j8lpyl/T/apm-install-dir-11596-96939-ws8z49/node_modules/autocomplete-ctags/node_modules/ctags
> node-gyp rebuild

  CC(target) Release/obj.target/ctags/src/readtags.o
  CXX(target) Release/obj.target/ctags/src/tags.o
  CXX(target) Release/obj.target/ctags/src/tag-finder.o
  CXX(target) Release/obj.target/ctags/src/tag-reader.o
  SOLINK_MODULE(target) Release/ctags.node

ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [Release/runas.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/w_/4xqmt6ws6793zj5bxj8n3rf5j8lpyl/T/apm-install-dir-11596-96939-ws8z49/node_modules/autocomplete-ctags/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [Release/ctags.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/w_/4xqmt6ws6793zj5bxj8n3rf5j8lpyl/T/apm-install-dir-11596-96939-ws8z49/node_modules/autocomplete-ctags/node_modules/ctags
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/doebel/.atom/.apm/.apmrc" "--userconfig" "/Users/doebel/.atom/.apmrc" "install" "/private/var/folders/w_/4xqmt6ws6793zj5bxj8n3rf5j8lpyl/T/d-11596-96939-18va4yr/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/w_/4xqmt6ws6793zj5bxj8n3rf5j8lpyl/T/apm-install-dir-11596-96939-ws8z49/npm-debug.log

**Comment by aki77** [comment]
See nodejs/node-gyp#734, you need to install both xcode 7 and the new command line tools.

https://github.com/nodejs/node/issues/2933
